### ISSUE TITLE
File size must be 0 when link

### ISSUE THREAD

**Issue by pbotsaris** [Pbotsaris/my_tar#10]
https://github.com/Pbotsaris/my_tar/blob/5ead8dd123f0b69cbbffc3efbcb5c7bacbe28919/src/file_handling.c#L27-L28

According to the [tar  manual](https://www.gnu.org/software/tar/manual/html_node/Standard.html), the size should be specified as 0 if the file in question is a link. 

Quoting from the manual:
> "The size field is the size of the file in bytes; linked files are archived with this field specified as zero."

**Comment by khalilmasri** [comment]
I assume this after compressing?

I would read about more.

**Comment by pbotsaris** [comment]
No, if the file is a link then it has 0 bytes because it is a link, not a real file I'd assume.

```
if(stat.t_mode != S_IFLNK)
  my_itoa(header->size, stats.st_size, DECIMAL); 
else
  header->size[0] = '0';
```

**Comment by khalilmasri** [comment]
Issue has been resolved
