### ISSUE TITLE
enum bool_t with swapped values

### ISSUE THREAD

**Issue by pbotsaris** [Pbotsaris/my_tar#4]
@khalilmasri 

https://github.com/Pbotsaris/my_tar/blob/0197fe731a29059e0a2236b2f99824c2312c5d5f/src/my_tar.h#L74-L79

Enum members are just int values so the first item is 0, the second is 1, the third is 2, and so on.   On the other hand, `TRUE` is generally represented by `1` while `FALSE` by `0`. However,  if we have `TRUE` and `FALSE` declared in the `enum bool_t` is this order then `TRUE = 0` and `FALSE = 1`.

Try this and check it out:
```
bool_t bolean = FALSE;
Try printf("%i",  bolean);
//  -> 1
```

**Comment by khalilmasri** [comment]
I deleted bool_t because I had some errors with it and conflict with bool_f.

Since we have the same header for all files now we can keep one enum bool and add an Error to it to know when its value is ERROR.

Tell me what you think.

**Comment by pbotsaris** [comment]
Sure. We can call it `bool_f` or `bool_t`. To me, it doesn't matter. But the issue of assigning the wrong int value to `TRUE` remains. 

Also,  `bool_t` stands for boolean type. What is the meaning `f`? I notice that you also use `flag_f`.  Just to better understand the code.
