### ISSUE TITLE
Consolidate if statement

### ISSUE THREAD

**Issue by pbotsaris** [Pbotsaris/my_tar#5]
@khalilmasri 

https://github.com/Pbotsaris/my_tar/blob/0197fe731a29059e0a2236b2f99824c2312c5d5f/src/option.c#L60-L62

Couldn't this be consolidated as a single if statement?

```
if (format[index][0] == '-' && (flag_opt = check_spam(flag_opt)) == NONE )
{
// (...)				
}				
```

**Comment by khalilmasri** [comment]
LOL yes!!
