### ISSUE TITLE
Always get error upon passing options

### ISSUE THREAD

**Issue by pbotsaris** [Pbotsaris/my_tar#6]
<img width="1792" alt="Screenshot 2021-06-23 at 23 52 43" src="https://user-images.githubusercontent.com/53109089/123173089-56abce80-d47e-11eb-8869-924343853c2f.png">

@khalilmasri 
I am getting an issue with the flags where I always get this error.  Maybe I am passing the wrong options but let's chat about it tomorrow.

**Comment by khalilmasri** [comment]
Sure, it works as intended for now, we may work on it more when we start configuring each flag.

**Comment by pbotsaris** [comment]
Sounds good. Let's chat later today so we can better understand the intention. I also created a little logic in`main` return if no arguments are passed.  
We get memory problems in the `printf("mode in char(octal): %s\n", header->mode);` because header->mode is not initialized when no arguments as we stand now.
