### ISSUE TITLE
Link Files

### ISSUE THREAD

**Issue by pbotsaris** [Pbotsaris/my_tar#9]
https://github.com/Pbotsaris/my_tar/blob/5ead8dd123f0b69cbbffc3efbcb5c7bacbe28919/src/file_handling.c#L30-L31

`stats.st_nlink` will return the number of links a file has not the name of the link or `linkname`. 

We probably need to check if the file is a link then use [lstat()](https://linux.die.net/man/2/lstat) to gather the link information.

**Comment by khalilmasri** [comment]
We should only get linkname
